/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Data.GameCharacter;
import Data.TutorialCard;
import Logic.ElementsInstantiation;

/**
 *
 * @author samyg
 */
public class TutorialPanel extends javax.swing.JPanel {
    private int currentTutorial;
    private GameCharacter tutorialMan = new GameCharacter(ElementsInstantiation.staticIcon("The_Barbarian.png"), "Hombre Tutorial", "");
    private TutorialCard card1 = new TutorialCard(tutorialMan, "Hola, bienvenido a *inserte nombre del juego*. Este es un juego simple de decisiones. Da click en cualquiera de los dos paneles a los costados de la imagen para continuar. ", "Bienvenida");
    private TutorialCard card2 = new TutorialCard(tutorialMan, "Abajo ahora puedes ver una fecha que representa un día al azar en la oficina.", "Fecha");
    private TutorialCard card3 = new TutorialCard(tutorialMan, "Arriba ahora puedes observar el panel de información: A la izquierda está el ícono de personaje, tu usuario y puesto en la compañía. Y a la derecha están las estadísticas.", "Panel superior");
    private TutorialCard card4 = new TutorialCard(tutorialMan, "Las estadísticas, en orden descendiente, corresponden a la reputación de la empresa, el dinero de la empresa, la felicidad de los trabajadores y el impacto ambiental de la empresa.", "Estadísticas");
    private TutorialCard card5 = new TutorialCard(tutorialMan, "El panel de la derecha de la imagen representa el Sí y el de la izquierda de ésta el No. Tus decisiones afectarán a las estadísticas. Si alguna de las estadísticas llega al mínimo o al tope, perderás la partida.", "Decisiones");
    private TutorialCard card6 = new TutorialCard(tutorialMan, "Si logras superar todas las cartas sin que ninguna de las estadísticas llegue a algún extremo ganarás la partida. Adelante, da click a alguno de los paneles para empezar a jugar.", "Ganar");
    
    public int getCurrentTutorial() {
        return currentTutorial;
    }

    public void setCurrentTutorial(int CurrentTutorial) {
        this.currentTutorial = CurrentTutorial;
    }
    /**
     * Creates new form MeCagoEnLaPuta
     */
    public TutorialPanel() {
        initComponents();
        
        this.currentTutorial = 1;
        statPanel.setVisible(false);
        dateLabel.setVisible(false);
        paintCard(card1);
    }
    
    private void paintCard(TutorialCard card) {
        situationDescription.setText(card.getAspectToTeach()+": " + card.getSituation());
        characterIconLabel.setIcon(card.getCharacter().getCharacterIcon());
        characterNameLabel.setText(card.getCharacter().getName());
    }
    
    private void secondCard() {
        dateLabel.setVisible(true);
        paintCard(card2);
    }
    
    private void thirdCard() {
        statPanel.setVisible(true);
        paintCard(card3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        datePanel = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        characterNameLabel = new javax.swing.JLabel();
        characterIconLabel = new javax.swing.JLabel();
        situationPane = new javax.swing.JScrollPane();
        situationDescription = new javax.swing.JTextArea();
        goLeftPanel = new javax.swing.JPanel();
        noLabel = new javax.swing.JLabel();
        goRightPanel = new javax.swing.JPanel();
        yesLabel = new javax.swing.JLabel();
        statPanel = new javax.swing.JPanel();
        statusBar = new javax.swing.JProgressBar();
        moneyBar = new javax.swing.JProgressBar();
        happinessBar = new javax.swing.JProgressBar();
        environmentBar = new javax.swing.JProgressBar();
        username = new javax.swing.JLabel();
        playerIconLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        businessName = new javax.swing.JTextArea();
        statusIcon = new javax.swing.JLabel();
        happinessIcon = new javax.swing.JLabel();
        environmentIcon = new javax.swing.JLabel();
        moneyIcon = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(58, 78, 122));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datePanel.setBackground(new java.awt.Color(94, 131, 186));

        dateLabel.setBackground(new java.awt.Color(94, 131, 186));
        dateLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("GUI/Bundle"); // NOI18N
        dateLabel.setText(bundle.getString("TutorialPanel.dateLabel.text")); // NOI18N

        javax.swing.GroupLayout datePanelLayout = new javax.swing.GroupLayout(datePanel);
        datePanel.setLayout(datePanelLayout);
        datePanelLayout.setHorizontalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        datePanelLayout.setVerticalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datePanelLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(dateLabel))
        );

        background.add(datePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 550, 50));

        cardPanel.setBackground(new java.awt.Color(194, 210, 233));

        characterNameLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        characterNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        characterNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        characterNameLabel.setText(bundle.getString("TutorialPanel.characterNameLabel.text")); // NOI18N

        characterIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/The_Jester.png"))); // NOI18N
        characterIconLabel.setText(bundle.getString("TutorialPanel.characterIconLabel.text")); // NOI18N

        situationDescription.setEditable(false);
        situationDescription.setBackground(new java.awt.Color(255, 255, 255));
        situationDescription.setColumns(20);
        situationDescription.setForeground(new java.awt.Color(0, 0, 0));
        situationDescription.setLineWrap(true);
        situationDescription.setRows(5);
        situationDescription.setText(bundle.getString("TutorialPanel.situationDescription.text")); // NOI18N
        situationDescription.setWrapStyleWord(true);
        situationDescription.setBorder(null);
        situationPane.setViewportView(situationDescription);

        goLeftPanel.setBackground(new java.awt.Color(194, 210, 233));
        goLeftPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goLeftPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goLeftPanelMouseClicked(evt);
            }
        });

        noLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        noLabel.setForeground(new java.awt.Color(0, 0, 0));
        noLabel.setText(bundle.getString("TutorialPanel.noLabel.text")); // NOI18N

        javax.swing.GroupLayout goLeftPanelLayout = new javax.swing.GroupLayout(goLeftPanel);
        goLeftPanel.setLayout(goLeftPanelLayout);
        goLeftPanelLayout.setHorizontalGroup(
            goLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, goLeftPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(noLabel)
                .addGap(27, 27, 27))
        );
        goLeftPanelLayout.setVerticalGroup(
            goLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(goLeftPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(noLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        goRightPanel.setBackground(new java.awt.Color(194, 210, 233));
        goRightPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goRightPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goRightPanelMouseClicked(evt);
            }
        });

        yesLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        yesLabel.setForeground(new java.awt.Color(0, 0, 0));
        yesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yesLabel.setText(bundle.getString("TutorialPanel.yesLabel.text")); // NOI18N

        javax.swing.GroupLayout goRightPanelLayout = new javax.swing.GroupLayout(goRightPanel);
        goRightPanel.setLayout(goRightPanelLayout);
        goRightPanelLayout.setHorizontalGroup(
            goRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, goRightPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(yesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        goRightPanelLayout.setVerticalGroup(
            goRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, goRightPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yesLabel)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(situationPane)
                    .addGroup(cardPanelLayout.createSequentialGroup()
                        .addComponent(goLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(characterIconLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(characterNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(situationPane, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(goLeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(characterIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(goRightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(characterNameLabel)
                .addContainerGap())
        );

        background.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 200, -1, -1));

        statPanel.setBackground(new java.awt.Color(94, 131, 186));

        statusBar.setMaximum(120);

        moneyBar.setMaximum(120);

        happinessBar.setMaximum(120);

        environmentBar.setMaximum(120);

        username.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText(bundle.getString("TutorialPanel.username.text")); // NOI18N

        playerIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/empresarioicono.png"))); // NOI18N
        playerIconLabel.setText(bundle.getString("TutorialPanel.playerIconLabel.text")); // NOI18N

        businessName.setEditable(false);
        businessName.setBackground(new java.awt.Color(94, 131, 186));
        businessName.setColumns(20);
        businessName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        businessName.setLineWrap(true);
        businessName.setRows(5);
        businessName.setText(bundle.getString("TutorialPanel.businessName.text")); // NOI18N
        businessName.setWrapStyleWord(true);
        businessName.setBorder(null);
        businessName.setPreferredSize(new java.awt.Dimension(280, 20));
        jScrollPane.setViewportView(businessName);

        statusIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/reputacionIcon.png"))); // NOI18N
        statusIcon.setText(bundle.getString("TutorialPanel.statusIcon.text")); // NOI18N

        happinessIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/felicidadIcon.png"))); // NOI18N
        happinessIcon.setText(bundle.getString("TutorialPanel.happinessIcon.text")); // NOI18N

        environmentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/arbolIcon.png"))); // NOI18N
        environmentIcon.setText(bundle.getString("TutorialPanel.environmentIcon.text")); // NOI18N

        moneyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/dineroIcon.png"))); // NOI18N
        moneyIcon.setText(bundle.getString("TutorialPanel.moneyIcon.text")); // NOI18N

        javax.swing.GroupLayout statPanelLayout = new javax.swing.GroupLayout(statPanel);
        statPanel.setLayout(statPanelLayout);
        statPanelLayout.setHorizontalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statPanelLayout.createSequentialGroup()
                        .addComponent(playerIconLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(statPanelLayout.createSequentialGroup()
                                .addComponent(username)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(happinessBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(environmentBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(moneyBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusIcon)
                    .addComponent(happinessIcon)
                    .addComponent(environmentIcon)
                    .addComponent(moneyIcon))
                .addContainerGap())
        );
        statPanelLayout.setVerticalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusIcon)
                    .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(username)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(statPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(moneyBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moneyIcon))
                        .addGap(12, 12, 12)
                        .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(happinessBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(happinessIcon))
                        .addGap(12, 12, 12)
                        .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(environmentBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(environmentIcon)))))
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(playerIconLabel))
        );

        background.add(statPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goLeftPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goLeftPanelMouseClicked
        int i = currentTutorial;
        switch (i) {
            case 1:
                secondCard();
                setCurrentTutorial(i+1);
                break;
            case 2:
                thirdCard();
                setCurrentTutorial(i+1);
                break;
            case 3:
                paintCard(card4);
                setCurrentTutorial(i+1);
                break;
            case 4:
                paintCard(card5);
                setCurrentTutorial(i+1);
                break;
            case 5:
                paintCard(card6);
                setCurrentTutorial(i+1);
                break;
            case 6:
                MainFrame.initiateGameMenu(this);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_goLeftPanelMouseClicked

    private void goRightPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goRightPanelMouseClicked
        int i = currentTutorial;
        switch (i) {
            case 1:
                secondCard();
                setCurrentTutorial(i+1);
                break;
            case 2:
                thirdCard();
                setCurrentTutorial(i+1);
                break;
            case 3:
                paintCard(card4);
                setCurrentTutorial(i+1);
                break;
            case 4:
                paintCard(card5);
                setCurrentTutorial(i+1);
                break;
            case 5:
                paintCard(card6);
                setCurrentTutorial(i+1);
                break;
            case 6:
                MainFrame.initiateGameMenu(this);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_goRightPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextArea businessName;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel characterIconLabel;
    private javax.swing.JLabel characterNameLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JPanel datePanel;
    private javax.swing.JProgressBar environmentBar;
    private javax.swing.JLabel environmentIcon;
    private javax.swing.JPanel goLeftPanel;
    private javax.swing.JPanel goRightPanel;
    private javax.swing.JProgressBar happinessBar;
    private javax.swing.JLabel happinessIcon;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JProgressBar moneyBar;
    private javax.swing.JLabel moneyIcon;
    private javax.swing.JLabel noLabel;
    private javax.swing.JLabel playerIconLabel;
    private javax.swing.JTextArea situationDescription;
    private javax.swing.JScrollPane situationPane;
    private javax.swing.JPanel statPanel;
    private javax.swing.JProgressBar statusBar;
    private javax.swing.JLabel statusIcon;
    private javax.swing.JLabel username;
    private javax.swing.JLabel yesLabel;
    // End of variables declaration//GEN-END:variables
}
